package cn.navigational.dbfx.config

const val APP_STYLE = "css/app_style.css"
const val APP_ICON = "assets/icons/icon.svg"
const val OPEN_ICON = "assets/icons/db/mini/open.svg"
const val CON_MINI_ICON = "assets/icons/mini/con.svg"
const val DIS_CON_ICON = "assets/icons/mini/dis_con.svg"
const val SQL_TER_ICON = "assets/icons/mini/terminal.svg"
const val FLUSH_ICON = "assets/icons/mini/flush.svg"
const val EDIT_ICON = "assets/icons/mini/edit.svg"
const val MYSQL_ICON = "assets/icons/db/mini/mysql.svg"
const val SCHEME_ICON = "assets/icons/db/mini/folder.svg"
const val PG_ICON = "assets/icons/db/mini/postgres.svg"
const val MYSQL_SCHEME_ICON = "assets/icons/db/mini/my_scheme.svg"
const val PG_DB_ICON = "assets/icons/db/mini/pg_db.svg"
const val MYSQL_COLLATION_ICON = "assets/icons/db/mini/my_collation.svg"
const val MYSQL_USER_ICON = "assets/icons/db/mini/my_user.svg"
const val TABLE_ICON = "assets/icons/db/table.svg"
const val TABLE_FIELD_ICON = "assets/icons/db/mini/field.svg"
const val PG_ROLE_ICON = "assets/icons/db/mini/pg_role.svg"

//table controller icon
const val FIRST_PAGE_ICON = "assets/icons/table/first_page.svg"
const val LAST_PAGE_ICON = "assets/icons/table/last_page.svg"
const val LAST_ICON = "assets/icons/table/last.svg"
const val NEXT_ICON = "assets/icons/table/next.svg"
const val TABLE_FLUSH_ICON = "assets/icons/table/flush.svg"
const val SEARCH_ICON = "assets/icons/table/search_icon.svg"
const val ADD_ROW_ICON = "assets/icons/table/add.svg"
const val DEL_ROW_ICON = "assets/icons/table/del.svg"
const val ASC_ICON = "assets/icons/table/asc.svg"
const val DES_ICON = "assets/icons/table/des.svg"

//table field icon
const val NUMBER_FIELD = "assets/icons/table/field/number.svg"
const val STRING_FIELD = "assets/icons/table/field/letter.svg"
const val DATE_TIME_FIELD = "assets/icons/table/field/date_time.svg"